### ISSUE TITLE
(evolve) function

### ISSUE THREAD

**Issue by vadim0x60** [bakirillov/clojured-1dca#1]
```
(defn evolve [epochs start rule]
  (let
    [generations (atom [start])]
    (last (repeatedly 
      epochs #(reset! generations (into [] (concat @generations [(into [] (next-generation (last @generations) rule))]))))
    ))
)
```

Is the most non-functional piece of code I have seen written in Clojure :)
Why not

```
(defn evolve [epochs start rule]
  (take epochs (iterate #(vec (next-generation % rule)) start)))
```

?

**Comment by bakirillov** [comment]
Basically, because I was going to make jpeg frames for Quil (https://github.com/quil/quil), which would be more comfortable to do with (repeatedly epochs ....) that give away lists like ((first-state) (first-state second-state) (first-state second-state third-state)....), but did not do it.
